name: Update RSS Feeds

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run feed parser and translator
        run: python main.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/translated_feeds.json
          git diff --staged --quiet || git commit -m "Update translated feeds"
          git push https://x-access-token:$GH_TOKEN}@github.com/trucpd/rss-translator.git